### ISSUE TITLE
theme-styles not working

### ISSUE THREAD

**Issue by 0ArchLinux0** [nathanreyes/v-calendar#1032]
```vue
<v-calendar
    :theme-styles='themeStyles'
  >
  </v-calendar>
```

```vue
data() {
    return {
      themeStyles: {
        wrapper: { 
          background: 'linear-gradient(to bottom right, #ff5050, #ff66b3)',
          color: '#fafafa' 
        }
      },
```

this doesn't worked for me
Instead editing css did the trick.
```css
.vc-pane-container {
  background: linear-gradient(to bottom right, #ff5050, #ff66b3);
  color: #fafafa;
}
```
