### ISSUE TITLE
Prefer the old .vc-theme over polluting :root

### ISSUE THREAD

**Issue by micDropper** [nathanreyes/v-calendar#1287]
I noticed in 2158279460fe55d6a9f0c56bfeb260452b04ae8f the theme variable scope was bumped from the `.vc-theme` class up to `:root`. This forces users to pollute their global variables and may cause possible collisions with other libraries that also use a `.vc-` prefix in their styles, such as [vue-color](https://github.com/ckpack/vue-color) for example. Is there some functionality that requires the variables to be at the `:root` level?

For projects using scss, the `.vc-` class naming convention isn't a huge deal since we can scope the `v-calendar` styles to a parent class, but `:root` requires us to manually drop in a copy of the root variables:

```scss
//scss
.my-date-picker {
  // redeclare all :root variables scoped to .my-date-picker to prevent collisions at :root
  --vc-white: #ffffff;
  --vc-black: #000000;
  ...

  @import 'node_modules/v-calendar/dist/style';
}
```

How would you feel about re-scoping them to a class? That would allow this:
```scss
//scss
.my-date-picker {
  @import 'node_modules/v-calendar/dist/style';

  .vc-theme.vc-theme {
    // override variables here to customize styles
    // minimal maintenance + no collisions :)
  }
};
```
