### ISSUE TITLE
Calendar inherits Default Button Styles

### ISSUE THREAD

**Issue by simedia-fabianamhof** [nathanreyes/v-calendar#1327]
In the newer Versions of V-Calendar, some div's got replaced with buttons.
Since then, all Buttons inherit the default styles and therefore the widget does not have the same look as in the [documentation](https://vcalendar.io/calendar/layouts.html).

![image](https://github.com/nathanreyes/v-calendar/assets/132550726/e0924992-0b08-40e6-b233-bc03d59cce99)

In my opinion, it would be better if within the component the default button styles are replaced to have the same look as in the previous versions.

At the moment i use the following workaround:
```css
.vc-container button {
  background-color: transparent !important;
  font-family: inherit;
}
.vc-nav-container button {
  font-family: inherit;
}

.vc-nav-container button:not(.is-active) {
  background-color: transparent !important;
}
```
