### ISSUE TITLE
bootstrap 4 class conflict

### ISSUE THREAD

**Issue by R00118189** [nathanreyes/v-calendar#291]
Hi, I was exited to use v-calendar however it applies somehow 
```css
*, :after, :before {
    box-sizing: inherit;
}
``` 
and affects whole layout i tried on two different bootstrap themes and unfortunately am not able to tackle this.

any suggestions?
