### ISSUE TITLE
How can we disable hover and focus of each day of DatePicker?

### ISSUE THREAD

**Issue by manabuo** [nathanreyes/v-calendar#600]
When a day is touched on DatePicker, the date has tinted color with focus or hover attributes. I do not want these. How can we cancel these?

Or, when focus is lost by touching on another element, the color will be just selected attribute color when selected or the selected color is gone when unselected. 

Can we at least blur by script?

**Comment by aziev** [comment]
You can override CSS variables:

```css
.vc-container {
    --day-content-bg-color-hover: inherit;
    --day-content-bg-color-focus: inherit;
}
```

Make sure your styles has higher priority than defaults
