### ISSUE TITLE
[question] Examples

### ISSUE THREAD

**Issue by alfligno** [nathanreyes/v-calendar#660]
Does the example are being shared?
I can't seem to find it on the docs, though there is `demo.html` but it does not look like the example page,
I'm trying to work with the calendar, which uses custom slot :)

**Comment by trenzasoft** [comment]
I need to use Custom Calendars with todo but cant find any code block. can some one help me here?

**Comment by alfligno** [comment]
In my case, I copy on how the view was made on this [link](https://vcalendar.io/)
```vue
<v-calendar
	class='v-calendar w-100'
	ref="calendar"
	v-bind:min-date='calendar.minDate'
	v-bind:max-date='calendar.maxDate'>
	<template slot="day-content" class='h-100' scope='{day, dayEvents, attributes, attributesMap}'>
		<div class="flex flex-column h-100 overflow-hidden">
			<span class="day-label text-sm text-gray-900">{{day.day}}</span>
			<div class="flex-grow h-100 calendar-event" v-if='eventDates.includes(formatDate(day).format("YYYY-MM-DD"))'>
				<small
					@click.prevent='$router.push(`${root_link}/calendars/${event.post_type}/${event.slug}`)'
					class="badge mb-2"
					v-for='event in events(formatDate(day).format("YYYY-MM-DD"))'
					style='white-space: pre-wrap; cursor: pointer;'
					v-bind:class='{"badge-info": event.post_type==="webinar", "badge-danger": event.post_type==="event"}'>{{event.title}}</small>
			</div>
		</div>
	</template>
</v-calendar>
```

```css
.v-calendar >>> .vc-day {
	padding: 0 5px 3px;
	border: 1px solid #e4e4e4;
	min-height: 100px;
	height: 100px;
	max-width: 115px;
	overflow-y: auto;
}
.v-calendar >>> .vc-day.weekday-7,
.v-calendar >>> .vc-day.weekday-1
{
	background-color: #eff8ff;
}
.v-calendar >>> .calendar-event{
	overflow-y: auto;
	-ms-overflow-style: none;  /* Internet Explorer 10+ */
  scrollbar-width: none;  /* Firefox */
}
.v-calendar >>> .calendar-event::-webkit-scrollbar {
	display: none;
}
```
